#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
MTEH Modification Report Generator
Generated by ChatGPT

Compares current mteh.txt with a snapshot version, producing a Markdown report.
Used for debugging and verification.
"""

import datetime

CURRENT_FILE = "../mteh.txt"
SNAPSHOT_FILE = "../versions/v0.1.3/mteh_v0.1.3.txt"
OUTPUT_FILE = "./mteh_modification_report.md"

# Map structure codes to symbols for readability
STRUCTURE_MAP = {
    "0": "none",
    "1": "⿰",
    "2": "⿱",
    "3": "⿲",
    "4": "⿳",
    "5": "⿴",
    "6": "⿵",
    "7": "⿶",
    "8": "⿷",
    "9": "⿸",
    "10": "⿹",
    "11": "⿺",
    "12": "⿻"
}

def read_mteh(file_path):
    """Read MTEH file and return dict of character -> [char, pinyin, hint, freq1, freq2, structure]"""
    data = {}
    with open(file_path, encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split(maxsplit=5)
            if len(parts) < 6:
                # handle missing columns
                parts += [""] * (6 - len(parts))
            char, pinyin, hint, freq1, freq2, structure = parts
            data[char] = [char, pinyin, hint, freq1, freq2, structure]
    return data

def structure_repr(code):
    """Return human-readable structure representation"""
    return f"{STRUCTURE_MAP.get(code, code)} ({code})"

def generate_report(current, snapshot):
    report = []

    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    report.append(f"# MteH Modification Report\n")
    report.append(f"**Generated:** {timestamp}\n")
    report.append(f"**Current file:** `{CURRENT_FILE}`  \n**Snapshot file:** `{SNAPSHOT_FILE}`  \n")
    report.append("_Generated using Python code generated by ChatGPT_\n")

    # --- Added / Removed ---
    current_chars = set(current.keys())
    snapshot_chars = set(snapshot.keys())

    added = sorted(current_chars - snapshot_chars)
    removed = sorted(snapshot_chars - current_chars)

    report.append(f"## Characters Added ({len(added)})")
    report.append(" ".join(f"`{c}`" for c in added) or "None")

    report.append("\n### Full Data for Added Characters")
    for char in added:
        char_data = current[char]
        report.append(f"`{char}` : {char_data[0]} {char_data[1]} {char_data[2]} {char_data[3]} {char_data[4]} {char_data[5]}\n")

    report.append(f"\n## Characters Removed ({len(removed)})")
    report.append(" ".join(f"`{c}`" for c in removed) or "None")

    # --- Hint changes ---
    hint_changes = [(c, snapshot[c][2], current[c][2])
                    for c in current_chars & snapshot_chars
                    if snapshot[c][2] != current[c][2]]
    report.append(f"\n## Hint Changes ({len(hint_changes)})")
    if hint_changes:
        for char, old, new in hint_changes:
            report.append(f"`{char}`: '{old}' -> '{new}'\n")
    else:
        report.append("No hint changes detected.")

    # --- Pinyin changes ---
    pinyin_changes = [(c, snapshot[c][1], current[c][1])
                      for c in current_chars & snapshot_chars
                      if snapshot[c][1] != current[c][1]]
    report.append(f"\n## Pinyin Changes ({len(pinyin_changes)})")
    if pinyin_changes:
        for char, old, new in pinyin_changes:
            report.append(f"`{char}`: '{old}' -> '{new}'\n")
    else:
        report.append("No pinyin changes detected.")

    # --- Structure changes ---
    structure_changes = [(c, snapshot[c][5], current[c][5])
                         for c in current_chars & snapshot_chars
                         if snapshot[c][5] != current[c][5]]
    report.append(f"\n## Structure Changes ({len(structure_changes)})")
    if structure_changes:
        for char, old, new in structure_changes:
            report.append(f"`{char}`: {structure_repr(old)} -> {structure_repr(new)}\n")
    else:
        report.append("No structure changes detected.")

    # --- Column 5 check (should not change) ---
    for char in current_chars & snapshot_chars:
        if current[char][4] != snapshot[char][4]:
            report.append(f"ERROR: Column 5 changed for `{char}`: '{snapshot[char][4]}' -> '{current[char][4]}'\n")

    return "\n".join(report)

def main():
    current = read_mteh(CURRENT_FILE)
    snapshot = read_mteh(SNAPSHOT_FILE)
    report_md = generate_report(current, snapshot)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write(report_md)
    print(f"Modification report written to {OUTPUT_FILE}")

if __name__ == "__main__":
    main()

